default_root_dir: 'model_ckpts'
max_epochs: 50
strategy: "ddp"
accelerator: "gpu"
devices: [0, 1, 2]
num_workers: 8 # number of workers for each dataloader
accumulate_grad_batches: 1 # don't accumulate grads