root_dir: './data/creste'
infill_strat: 'IDW'
scans: 1
skip_factor: 2
map_size: [25.6, 25.6] # Do not change
voxel_size: [0.1, 0.1]  # Do not change
map_range: [-12.8, -12.8, -2, 12.8, 12.8, 1] # xmin ymin zmin xmax ymax zmax
skip_sequences: []
img_h: 512
img_w: 612
ds_rgb: 1 # Downsamples images 8 times
ds_gt_depth: 4 # Downsamples depth 24 times to fit in GPU memory
remap_labels: True
do_augmentation: True
location_resampling: False
datasets: 
  - name: "3d_ssc"
    tasks: ["3d_ssc"]

camera_augmentation:
  brightness: 0.5
  contrast: 0.5
  saturation: 0.5
  hue: 0.3
pc_augmentation:
  - name: "rotate"
    max_rotation: 0.0 # degrees
  - name: "translate"
    max_translation: 0.0 # meters
depth_augmentation:
  dropout_prob: 0.05
  calib_error_mean: [0.0, 0.0, 0.0] # tx ty theta
  calib_error_std: [3.0, 3.0, 0.02] # stdx stdy stdtheta (pixels, radians)
  depth_noise_std: 20.0 # LiDAR measurements error (mm)